version: "2"

services:
  mariadb:
    build: /home/robel/Documents/Inception/srcs/requirements/mariadb
    image: mariadb
    env_file:
      - .env
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - docker_network
    restart: always

  wordpress:
    build: /home/robel/Documents/Inception/srcs/requirements/wordpress
    image: wordpress
    env_file:
      - .env
    depends_on: 
      - mariadb
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - docker_network
    restart: always

  nginx:
    build: /home/robel/Documents/Inception/srcs/requirements/nginx
    image: nginx
    env_file:
      - .env
    ports:
      - 443:443
    depends_on: 
      - wordpress
    volumes:
      - wordpress_data:/var/www/html/wordpress
    networks:
      - docker_network
    restart: always

networks:
  docker_network:

volumes:
  mysql_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rkedida/data/mysql
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/rkedida/data/wordpress